from django.urls import path
from elearn import views

urlpatterns = [
    path('',views.index,name='index'),
    path('adminlogin',views.adminlogin,name='adminlogin'),
    path('Teachlogin',views.Teachlogin,name='Teachlogin'),
    path('Stulogin',views.Stulogin,name='Stulogin'),
    path('register',views.register,name='register'),
    path('logout',views.logout,name='logout'),
    path('adminhome',views.adminhome,name='adminhome'),
    path('Userslist',views.Userslist,name='Userslist'),
    path('Useredit/<int:id>',views.Useredit,name='Useredit'),
    path('deleteuser/<int:id>',views.deleteuser,name='deleteuser'),
    path('Courselist',views.Courselist,name='Courselist'),
    path('Courseadd',views.Courseadd,name='Courseadd'),
    path('Courseedit/<int:id>',views.Courseedit,name='Courseedit'),
    path('deletecourse/<int:id>',views.deletecourse,name='deletecourse'),
    path('Examlist',views.Examlist,name='Examlist'),
    path('Examadd',views.Examadd,name='Examadd'),
    path('Examedit/<int:id>',views.Examedit,name='Examedit'),
    path('deleteexam/<int:id>',views.deleteexam,name='deleteexam'),
    path('Marklist',views.Marklist,name='Marklist'),
    path('Markedit/<int:id>',views.Markedit,name='Markedit'),
    path('deletemark/<int:id>',views.deletemark,name='deletemark'),
    path('Materialslist',views.Materialslist,name='Materialslist'),
    path('deletematerial/<int:id>',views.deletematerial,name='deletematerial'),
    path('Teachhome',views.Teachhome,name='Teachhome'),
    path('viewteachpro',views.viewteachpro,name='viewteachpro'),
    path('Teachprofedit/<int:id>',views.Teachprofedit,name='Teachprofedit'),
    path('Teachlistmarks',views.Teachlistmarks,name='Teachlistmarks'),
    path('Markadd',views.Markadd,name='Markadd'),
    path('Teachlistmaterials',views.Teachlistmaterials,name='Teachlistmaterials'),
    path('Materialadd',views.Materialadd,name='Materialadd'),
    path('Stuhome',views.Stuhome,name='Stuhome'),
    path('viewstupro',views.viewstupro,name='viewstupro'),
    path('Stuprofedit/<int:id>',views.Stuprofedit,name='Stuprofedit'),
    path('Mycourseslist',views.Mycourseslist,name='Mycourseslist'),
    path('viewprogress',views.viewprogress,name='viewprogress'),
    path('Stuproadd',views.Stuproadd,name='Stuproadd'),
    path('Teachproadd',views.Teachproadd,name='Teachproadd'),
    path('viewmaterial',views.viewmaterial,name='viewmaterial'),
    path('payment',views.payment,name='payment'),
]