# Generated by Django 4.1.3 on 2022-11-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_courses_materials_marks_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='course',
        ),
        migrations.AddField(
            model_name='marks',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearn.exam'),
        ),
    ]
