# Generated by Django 4.1.3 on 2022-12-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0005_alter_materials_material_teachprofile_stuprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
