# Generated by Django 4.1.3 on 2022-12-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0006_alter_exam_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearn.courses'),
        ),
    ]
